---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: golang-test-pipeline-run
spec:
  pipelineRef:
    name: golang-test-pipeline
  params:
  - name: url
    value: "https://github.com/justin-lf/golang-tekton-hello-world"
  - name: package
    value: "github.com/justin-lf/golang-tekton-hello-world"
  workspaces:
  - name: shared-workspace
    persistentvolumeclaim:
      claimName: golang-source-pvc
  - name: nexuscreds
    secret:
      secretName: regcred