---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: golang-test-pipeline-run
spec:
  pipelineRef:
    name: golang-test-pipeline
  params:
    - name: "url"
      value: "{{ .Values.params.go-pipeline-url }}"
    - name: "package"
      value: "{{ .Values.params.go-package }}"
  workspaces:
    - name: shared-workspace
      persistentvolumeclaim:
        claimName: golang-source-pvc
    - name: nexuscreds
      secret:
        secretName: regcred