apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: kaniko-test-pipeline-with-chains
spec:
  workspaces:
  - name: shared-workspace
  - name: registry-creds
  params:
  - name: image
    description: reference of the image to build
  tasks:
  - name: fetch-repository
    taskRef:
      name: git-clone
    workspaces:
    - name: output
      workspace: shared-workspace
    params:
    - name: url
      value: "{{ .Values.params.url }}"
    - name: subdirectory
      value: ""
    - name: deleteExisting
      value: "true"
  - name: kaniko-chains
    taskRef:
      name: kaniko-chains
    runAfter:
    - fetch-repository
    workspaces:
    - name: source
      workspace: shared-workspace
    - name: dockerconfig
      workspace: registry-creds
    # Below not needed?
    # env: 
    # - name: REGISTRY
    # valueFrom: "{{ .Values.image.repository }}"
    # - name: DOCKERCONFIG_SECRET_NAME
    # valueFrom:
    # secretKeyRef: regcred
    params:
    - name: IMAGE
      value: $(params.image)
    - name: EXTRA_ARGS
      value:
        - --skip-tls-verify
  - name: verify-digest
    runAfter:
    - kaniko
    params:
    - name: digest
      value: $(tasks.kaniko-chains.results.IMAGE_DIGEST)
    taskSpec:
      params:
      - name: digest
      steps:
      - name: bash
        image: ubuntu
        script: |
          echo $(params.digest)
          case .$(params.digest) in
            ".sha"*) exit 0 ;;
            *)       echo "Digest value is not correct" && exit 1 ;;
          esac
  - name: verify-url
    runAfter:
    - kaniko-chains
    params:
    - name: url
      value: $(tasks.kaniko-chains.results.IMAGE_URL)
    taskSpec:
      params:
      - name: url
      steps:
      - name: bash
        image: ubuntu
        script: |
          echo $(params.url)
          case .$(params.url) in
            *"/kaniko-nocode") exit 0 ;;
            *)       echo "URL value is not correct" && exit 1 ;;
          esac
