---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: npm-test-pipeline-run
spec:
  pipelineRef:
    name: npm-test-pipeline
  params:
  - name: url
    value: "https://github.com/AustinAbro321/node_test"
  - name: path_context
    value: "server/"
  - name: args
    value: "test"
  workspaces:
  - name: shared-workspace
    persistentvolumeclaim:
      claimName: npm-source-pvc